[graph]
all-features = true

[advisories]
ignore = [
    # atty 0.2.14
    # Advisory: https://rustsec.org/advisories/RUSTSEC-2021-0145
    "RUSTSEC-2021-0145",

    # ansi_term 0.12.1
    # Advisory: https://rustsec.org/advisories/RUSTSEC-2021-0139
    "RUSTSEC-2021-0139",

    # ed25519-dalek 1.0.1
    # Advisory: https://rustsec.org/advisories/RUSTSEC-2022-0093
    "RUSTSEC-2022-0093",

    # atty 0.2.14
    # Advisory: https://rustsec.org/advisories/RUSTSEC-2024-0375
    "RUSTSEC-2024-0375",

    # derivative 2.2.0
    # Advisory: https://rustsec.org/advisories/RUSTSEC-2024-0388
    "RUSTSEC-2024-0388",
]
