tracing:
  json: false # change to `true` for production

rpc:
  endpoint: http://127.0.0.1:8899/

grpc:
  endpoint: http://127.0.0.1:10000/
  x_token: null

redis:
  endpoint: redis://127.0.0.1:6379/
  slot_finalized: solfees:finalized
  stream_key: solfees:events
  # increate for production: 3_000 / 4 / 2.5 / 60 = 5min
  stream_maxlen: 600
  stream_field_key: message
  epochs_key: solfees:epochs

listen_admin:
  bind: 127.0.0.1:8002
