tracing:
  json: false # change to `true` for production

redis:
  endpoint: redis://127.0.0.1:6379/
  stream_key: solfees:events
  stream_field_key: message
  epochs_key: solfees:epochs

listen_admin:
  bind: 127.0.0.1:8001

listen_rpc:
  bind: 127.0.0.1:8000
  body_limit: 16KiB # Maximum body size
  request_calls_max: 5 # Maximum number of calls in on request
  request_timeout: 60s # Request timeout (processed by dedicated tasks, see `pool_size`)
  request_queue_max: 5000 # Maximum number of requests in the queue (each request can contain max `request_calls_max` calls)
  streams_channel_capacity: 300 # Maximum number of messages in WebSocket channel before disconnect
  pool_size: 2 # Number of workers processing requests (WebSocket streams processed by separate task)
