tracing:
  json: false # change to `true` for production

redis:
  endpoint: redis://127.0.0.1:6379/
  stream_key: solfees:events
  stream_field_key: message

listen_admin:
  bind: 127.0.0.1:8001

listen_rpc:
  bind: 127.0.0.1:8000
  body_limit: 50KiB
  request_timeout: 60s
  request_queue_max: 1000
  streams_channel_capacity: 150
