name: Build and Deploy
on:
  # test purposes
  pull_request:
    branches:
      - 'master'
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - 'master'
  workflow_dispatch:
permissions:
  contents: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Install node_modules
        run: pnpm install
        working-directory: solfees-fe
      - name: Build application
        run: pnpm build
        working-directory: solfees-fe
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: solfees-fe/build